export const experiences = [
  {
    role: "Junior Software Developer",
    company: "Gate Institute",
    website: "https://www.gate-ai.eu/en/home/",
    period: "Jun 2023 – Present",
    projects: [
      {
        title: "Travel App",
        desc: "Developed a cross-platform travel app with React Native (Expo, TypeScript, Tailwind) featuring dynamic maps (Google Maps API), animated charts, multilingual support (EN/BG), secure API authentication, offline handling, push notifications, modular architecture, and seamless background geolocation. Optimized performance with React Query and Reanimated, delivering a smooth user experience across iOS, Android.",
        tech: [
          "React Native",
          "Expo",
          "TypeScript",
          "Tailwind",
          "Google Maps API",
          "React Query",
          "Zod",
          "SecureStore",
          "Geolocation",
          "Reanimated",
          "React Hook Form",
          "i18n-js",
        ],
      },
      {
        title: "City Living Lab",
        desc: "Developed a modular React/Vite dashboard for City Living Lab, visualizing air quality, noise, and pedestrian sensor stations on an interactive Mapbox map. Added live metric filtering, color-coded station details, EN/BG support, and an ECharts analysis workspace with date ranges, trend lines, and CSV export. Integrated cached REST API access through an Express proxy with Docker/Nginx deployment.",
        tech: [
          "React",
          "Vite",
          "Tailwind CSS",
          "React Router",
          "Zustand",
          "Mapbox",
          "react-map-gl",
          "ECharts",
          "Headless UI",
          "React Datepicker",
          "Framer Motion",
          "i18n",
          "Express Proxy",
          "Docker",
          "Nginx",
          "REST API",
        ],
      },
      {
        title: "City Living Lab API",
        desc: "Developed the FastAPI backend for the City Living Lab platform, providing endpoints for real-time and historical smart city data, including air quality, noise, and pedestrian data. Implements aggregation, GeoJSON outputs for mapping, authentication, caching, and optimized PostgreSQL queries to ensure fast, secure, and scalable access for the frontend platform.",
        tech: [
          "Python",
          "FastAPI",
          "SQLAlchemy",
          "PostgreSQL",
          "Uvicorn",
          "Gunicorn",
          "Redis Cache",
          "Pydantic",
          "Docker",
          "Authentication & Authorization",
        ],
      },
      {
        title: "Traffic Visualization",
        desc: "Developed a full-stack geospatial traffic analytics platform for Bulgaria, visualizing district and municipality indicators on an interactive Mapbox choropleth map. Added single-metric and correlation analysis modes, hover tooltips, region detail drawers, an optional NDVI overlay, and backend-driven metrics from PostgreSQL through a Node/Express API.",
        tech: [
          "React",
          "Vite",
          "Tailwind CSS",
          "Mapbox GL JS",
          "i18next",
          "Node.js",
          "Express",
          "PostgreSQL",
          "Docker",
          "Nginx",
          "GitHub Actions",
          "REST API",
        ],
      },
      {
        title: "EEA Air Quality Scraper",
        desc: "Built an automated Python pipeline to collect, clean, and store Sofia’s air quality data into PostgreSQL. Leveraged Selenium for robust web scraping, Pandas for data transformation, and psycopg2 for efficient database integration. Ensured reliability with error handling, retry logic, logging, and modular design, enabling continuous monitoring and analysis of environmental data at scale.",
        tech: ["Python", "PostgreSQL", "Pandas", "psycopg2", "Selenium"],
      },
    ],
  },
];
