export const experiences = [
  {
    role: "Junior Software Developer",
    company: "Gate Institute",
    website: "https://www.gate-ai.eu/en/home/",
    period: "Jun 2023 – Present",
    projects: [
      {
        title: "Travel App",
        desc: "Developed a cross-platform travel app with React Native (Expo, TypeScript, Tailwind) featuring dynamic maps (Google Maps API), animated charts, multilingual support (EN/BG), secure API authentication, offline handling, push notifications, modular architecture, and seamless background geolocation. Optimized performance with React Query and Reanimated, delivering a smooth user experience across iOS, Android.",
        tech: [
          "React Native",
          "Expo",
          "TypeScript",
          "Tailwind",
          "Google Maps API",
          "React Query",
          "Zod",
          "SecureStore",
          "Geolocation",
          "Reanimated",
          "React Hook Form",
          "i18n-js",
        ],
      },
      {
        title: "EEA Air Quality Scraper",
        desc: "Built an automated Python pipeline to collect, clean, and store Sofia’s air quality data into PostgreSQL. Leveraged Selenium for robust web scraping, Pandas for data transformation, and psycopg2 for efficient database integration. Ensured reliability with error handling, retry logic, logging, and modular design, enabling continuous monitoring and analysis of environmental data at scale.",
        tech: ["Python", "PostgreSQL", "Pandas", "psycopg2", "Selenium"],
      },
      {
        title: "City Living Lab",
        desc: "Developed a modular React/Vite dashboard for City Living Lab, visualizing air quality, noise, and pedestrian sensor stations on an interactive Mapbox map. Added live metric filtering, color-coded station details, EN/BG support, and an ECharts analysis workspace with date ranges, trend lines, and CSV export. Integrated cached REST API access through an Express proxy with Docker/Nginx deployment.",
        tech: [
          "React",
          "Vite",
          "Tailwind CSS",
          "React Router",
          "Zustand",
          "Mapbox",
          "react-map-gl",
          "ECharts",
          "Headless UI",
          "React Datepicker",
          "Framer Motion",
          "i18n",
          "Express Proxy",
          "Docker",
          "Nginx",
          "REST API",
        ],
      },
      {
        title: "City Living Lab API",
        desc: "Developed the FastAPI backend for the City Living Lab platform, providing endpoints for real-time and historical smart city data, including air quality, noise, and pedestrian data. Implements aggregation, GeoJSON outputs for mapping, authentication, caching, and optimized PostgreSQL queries to ensure fast, secure, and scalable access for the frontend platform.",
        tech: [
          "Python",
          "FastAPI",
          "SQLAlchemy",
          "PostgreSQL",
          "Uvicorn",
          "Gunicorn",
          "Redis Cache",
          "Pydantic",
          "Docker",
          "Authentication & Authorization",
        ],
      },
      {
        title: "Sofia Sensors",
        desc: "Created a web application displaying air quality, weather, and environmental sensor data across Sofia. Features interactive Mapbox map, dynamic heatmaps, historical and live charts, pollutant-based visual cues, and efficient API caching. This frontend is powered by the City Digital Twin Laboratory API, ensuring reliable, real-time access to urban environmental data.",
        tech: [
          "JavaScript",
          "Mapbox GL JS",
          "ECharts",
          "Turf JS",
          "Flatpickr",
          "REST API",
          "LocalStorage Caching",
        ],
      },
      {
        title: "City Digital Twin Laboratory API",
        desc: "Developed the FastAPI backend supporting Sofia Sensors, delivering endpoints for station metadata, measurements, historical aggregations, and heatmap predictions. Features authentication, caching, and optimized SQLAlchemy/PostgreSQL queries with Docker deployment to provide scalable, secure access for the Sofia Sensors frontend.",
        tech: [
          "Python",
          "FastAPI",
          "SQLAlchemy",
          "PostgreSQL",
          "Uvicorn",
          "Gunicorn",
          "Redis Cache",
          "Pydantic",
          "Docker",
          "Authentication & Authorization",
        ],
      },
    ],
  },
];
