export const experiences = [
  {
    role: "Software Developer",
    company: "Gate Institute",
    website: "https://www.gate-ai.eu/en/home/",
    period: "Jun 2023 – Present",
    projects: [
      {
        title: "Urban Sensing Data Platform",
        desc: "Built a multi-source Python platform that ingests MQTT/LoRa streams and external environmental data into PostgreSQL. Continuous ingestion and scheduled ETL workflows use buffering, retries, coverage checks, and safe historical backfills. Modular, tested services run in Docker Compose, with Linux/systemd managing continuous and scheduled workloads.",
        tech: ["Python", "PostgreSQL", "MQTT", "Pandas", "Docker", "Docker Compose", "Linux"],
      },
      {
        title: "City Living Lab API",
        desc: "Built a FastAPI service for City Living Lab station metadata, measurements, and raw sensor readings. API-key-protected endpoints provide filtering, pagination, and cached responses backed by PostgreSQL. The service is incrementally moving selected read-only metadata and current-measurement paths to Hadoop/Impala through an opt-in architecture.",
        tech: [
          "Python",
          "FastAPI",
          "SQLAlchemy",
          "PostgreSQL",
          "Uvicorn",
          "Gunicorn",
          "Redis Cache",
          "Pydantic",
          "Docker",
          "Authentication & Authorization",
        ],
      },
      {
        title: "Travel App",
        desc: "Built a React Native and Expo travel app for tracking trips across iOS and Android. Travelers can explore and edit journeys on a map, review trip-grouped timelines and history, and complete a bilingual EN/BG questionnaire. React Query supports optimistic journey updates, while cached reverse geocoding adds readable addresses to trips.",
        tech: [
          "React Native",
          "Expo",
          "TypeScript",
          "Tailwind",
          "Google Maps API",
          "React Query",
          "Zod",
          "SecureStore",
          "Geolocation",
          "Reanimated",
          "React Hook Form",
          "i18n-js",
        ],
      },
      {
        title: "City Living Lab",
        desc: "Built a React/Vite smart-city dashboard that maps air quality, noise, and pedestrian stations with Mapbox. Users can filter measurements, interpret color-coded values, inspect stations, and open a prefilled ECharts analysis view with date and time controls. The bilingual EN/BG interface supports CSV, JSON, and Excel exports; an Express proxy and Docker/Nginx support deployment.",
        tech: [
          "React",
          "Vite",
          "Tailwind CSS",
          "React Router",
          "Zustand",
          "Mapbox",
          "react-map-gl",
          "ECharts",
          "Headless UI",
          "React Datepicker",
          "Framer Motion",
          "i18n",
          "Express Proxy",
          "Docker",
          "Nginx",
          "REST API",
        ],
      },
      {
        title: "Traffic Visualization",
        desc: "Built a full-stack geospatial analytics platform for Bulgarian district and municipality indicators. An interactive Mapbox choropleth supports single-indicator and correlation analysis, with regional details and breakdowns for road safety, transport, and related data. The bilingual React/Vite frontend uses a Node/Express API backed by PostgreSQL, with Docker/Nginx deployment.",
        tech: [
          "React",
          "Vite",
          "Tailwind CSS",
          "Mapbox GL JS",
          "i18next",
          "Node.js",
          "Express",
          "PostgreSQL",
          "Docker",
          "Nginx",
          "GitHub Actions",
          "REST API",
        ],
      },
    ],
  },
];
